package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzr
  extends OptionalPendingResult
{
  private final zzb zzaiy;
  
  public zzr(PendingResult paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzb)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    zzaiy = ((zzb)paramPendingResult);
  }
  
  public final Result await()
  {
    return zzaiy.await();
  }
  
  public final Result await(long paramLong, TimeUnit paramTimeUnit)
  {
    return zzaiy.await(paramLong, paramTimeUnit);
  }
  
  public final void cancel()
  {
    zzaiy.cancel();
  }
  
  public final Result get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public final boolean isCanceled()
  {
    return zzaiy.isCanceled();
  }
  
  public final boolean isDone()
  {
    return zzaiy.isReady();
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback)
  {
    zzaiy.setResultCallback(paramResultCallback);
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    zzaiy.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  public final void zza(PendingResult.zza paramzza)
  {
    zzaiy.zza(paramzza);
  }
  
  public final Integer zzpa()
  {
    return zzaiy.zzpa();
  }
}

/* Location:
 * Qualified Name:     com.google.android.gms.common.api.internal.zzr
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */